baseURL = 'https://integralnaekologia.sk/'
locale = 'sk'
title = 'Integrálna ekológia'
author = 'Peter Viskup'
copyright = 'Peter Viskup'
theme = 'ananke'
text_color = 'green'
#body_classes = 'bg-green'
[params]
  description = 'Integrálna ekológia podľa encykliky Laudato si pápeža Františka'
  #site_logo = "img/earth-icon.png"
  featured_image = "/img/cover-frantisek.jpg"
  #featured_image_class = ""
  background_color_class = 'bg-dark-green'
